const dishes = [{
    id: 1,
    img:"https://s3.eu-central-1.amazonaws.com/kg.sbbar.storage/CqkLRrSVIMG_9866.jpg",
    title: "Фирменный SB - steak",
    desc: "Томагавк с фирменным соусом.",
    price: 999,
    rating: 2,
},{
    id: 2,
    img:"https://s3.eu-central-1.amazonaws.com/kg.sbbar.storage/IsuLgz69%D0%A1%D1%82%D0%B5%D0%B9%D0%BA_Pepper.png",
    title: "Стейк BRISKET",
    desc: "Томленная говядина, соус брискет",
    price: 750,
    rating: 3,
},{
    id: 3,
    img:"https://s3.eu-central-1.amazonaws.com/kg.sbbar.storage/MurcmHCNp.jpg",
    title: "Стейк Рибай",
    desc: "Рибай без кости.",
    price: 1000,
    rating: 4,
}, {
    id: 4,
    img: "https://s3.eu-central-1.amazonaws.com/kg.sbbar.storage/MurcmHCNp.jpg",
    title: "Стейк Рибай",
    desc: "Рибай без кости.",
    price: 1000,
    rating: 5,
},{
    id: 5,
    img:"https://s3.eu-central-1.amazonaws.com/kg.sbbar.storage/CqkLRrSVIMG_9866.jpg",
    title: "Фирменный SB - steak",
    desc: "Томагавк с фирменным соусом.",
    price: 999,
    rating: 2,
},{
    id: 6,
    img:"https://s3.eu-central-1.amazonaws.com/kg.sbbar.storage/IsuLgz69%D0%A1%D1%82%D0%B5%D0%B9%D0%BA_Pepper.png",
    title: "Стейк BRISKET",
    desc: "Томленная говядина, соус брискет",
    price: 750,
    rating: 3,
},{
    id: 7,
    img:"https://s3.eu-central-1.amazonaws.com/kg.sbbar.storage/CqkLRrSVIMG_9866.jpg",
    title: "Фирменный SB - steak",
    desc: "Томагавк с фирменным соусом.",
    price: 999,
    rating: 4,
},{
    id: 8,
    img:"https://s3.eu-central-1.amazonaws.com/kg.sbbar.storage/IsuLgz69%D0%A1%D1%82%D0%B5%D0%B9%D0%BA_Pepper.png",
    title: "Стейк BRISKET",
    desc: "Томленная говядина с орешками",
    price: 750,
    rating: 5,
},{
    id: 9,
    img:"https://s3.eu-central-1.amazonaws.com/kg.sbbar.storage/CqkLRrSVIMG_9866.jpg",
    title: "Фирменный SB - steak",
    desc: "Томагавк с фирменным соусом.",
    price: 999,
    rating: 5,
}]
export default dishes